# Generated by Django 4.2 on 2025-08-11 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("excel_path", models.CharField(max_length=500)),
                ("excel_sheet", models.CharField(max_length=255)),
                ("header_row_index", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SuperAdmin", "SuperAdmin"),
                            ("PiloteProcessus", "PiloteProcessus"),
                            ("Pilote", "Pilote"),
                            ("Utilisateur", "Utilisateur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plans_autorises", models.ManyToManyField(blank=True, to="pa.plan")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("act_id", models.CharField(max_length=9, unique=True)),
                ("titre", models.CharField(max_length=255)),
                ("statut", models.CharField(max_length=50)),
                ("priorite", models.CharField(max_length=50)),
                (
                    "budget_dzd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("p", models.BooleanField(default=False)),
                ("d", models.BooleanField(default=False)),
                ("c", models.BooleanField(default=False)),
                ("a", models.BooleanField(default=False)),
                ("j", models.IntegerField(blank=True, null=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                ("excel_fichier", models.CharField(max_length=255)),
                ("excel_feuille", models.CharField(max_length=255)),
                ("excel_row_index", models.IntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="pa.plan",
                    ),
                ),
                (
                    "responsables",
                    models.ManyToManyField(
                        blank=True, related_name="actions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
