# Generated by Django 4.2 on 2025-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="date_debut",
        ),
        migrations.RemoveField(
            model_name="action",
            name="date_fin",
        ),
        migrations.AddField(
            model_name="action",
            name="date_creation",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="date_realisation",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="delais",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="priorite",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="action",
            name="statut",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["statut"], name="pa_action_statut_e2c9e4_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["priorite"], name="pa_action_priorit_41ee2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["delais"], name="pa_action_delais_ced3d6_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["date_creation"], name="pa_action_date_cr_52bcf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["date_realisation"], name="pa_action_date_re_720337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["plan"], name="pa_action_plan_id_eed5f2_idx"),
        ),
    ]
