# Generated by Django 5.2.5 on 2025-08-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0003_notificationtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("date", "date"),
                            ("select", "select"),
                            ("tags", "tags"),
                            ("bool", "bool"),
                        ],
                        max_length=10,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("min", models.IntegerField(blank=True, null=True)),
                ("max", models.IntegerField(blank=True, null=True)),
                ("regex", models.CharField(blank=True, max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                (
                    "role_visibility",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("SA_PP", "SA_PP"),
                            ("Pilote", "Pilote"),
                            ("Utilisateur", "Utilisateur"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="custom",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CustomFieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="pa.customfield",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
