# Generated by Django 5.2.5 on 2025-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0004_customfield_action_custom_customfieldoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="j",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
