# Generated by Django 5.2.5 on 2025-08-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0005_alter_action_j"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("cron", models.CharField(default="*/30 * * * *", max_length=100)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("plan", "plan"),
                            ("all", "all"),
                            ("active", "active"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("batch_size", models.IntegerField(default=500)),
                ("retry_on_lock", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("FAIL", "FAIL"),
                            ("PARTIAL", "PARTIAL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("dry_run", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pa.plan",
                    ),
                ),
            ],
        ),
    ]
