# Generated by Django 5.2.5 on 2025-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0007_dataqualityrule_dataqualityissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="act_id",
            field=models.CharField(db_index=True, max_length=9),
        ),
    ]
