# Generated by Django 4.2 on 2025-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pa", "0008_alter_action_act_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="act_id",
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="excel_row_index",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "LOW"),
                    ("MED", "MED"),
                    ("HIGH", "HIGH"),
                    ("CRITICAL", "CRITICAL"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "OPEN"),
                    ("RESOLVED", "RESOLVED"),
                    ("IGNORED", "IGNORED"),
                ],
                db_index=True,
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[("OK", "OK"), ("FAIL", "FAIL"), ("PARTIAL", "PARTIAL")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["excel_row_index"], name="pa_action_excel_r_ba5614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["actif"], name="pa_plan_actif_f9ac8a_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["nom"], name="pa_plan_nom_da6401_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["excel_path"], name="pa_plan_excel_p_8da259_idx"
            ),
        ),
    ]
