# Generated by Django 5.2.5 on 2025-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0009_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('cron', 'cron'), ('sync_fail', 'sync_fail'), ('quality_threshold', 'quality_threshold'), ('action_overdue', 'action_overdue'), ('manual', 'manual')], max_length=20)),
                ('cron', models.CharField(blank=True, max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('notify_email', 'notify_email'), ('run_quality', 'run_quality'), ('run_sync', 'run_sync'), ('export_report', 'export_report')], max_length=20)),
                ('action_params', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=10)),
                ('last_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('visible_for_roles', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('email', 'email'), ('report', 'report')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
