name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (lint + tests)
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8
      - name: Lint (black/isort/flake8)
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Django tests
        run: |
          python manage.py migrate --noinput
          python manage.py test --noinput -v 2

  frontend:
    name: Frontend (lint + build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        env:
          VITE_API_URL: "http://localhost:8000/api"
        run: npm run build

  docker:
    name: Docker images (dev & prod)
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dev (compose)
        run: |
          docker compose -f docker-compose.yml config >/dev/null
      - name: Build backend:prod
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/backend:latest
      - name: Build frontend:prod
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/frontend:latest

  e2e:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: paa
          POSTGRES_USER: paa
          POSTGRES_PASSWORD: paa
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U paa -d paa" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install backend deps
        run: |
          pip install -r requirements.txt
          pip install gunicorn
      - name: Migrate + seed
        env:
          DATABASE_URL: postgres://paa:paa@localhost:5432/paa
        run: |
          python manage.py migrate --noinput
          python manage.py seed_demo
      - name: Run backend (gunicorn)
        env:
          DATABASE_URL: postgres://paa:paa@localhost:5432/paa
          DJANGO_SETTINGS_MODULE: config.settings
          DJANGO_DEBUG: '0'
          ALLOWED_HOSTS: '*'
          CORS_ALLOWED_ORIGINS: 'http://localhost:5173'
        run: |
          nohup gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 60 &
          sleep 3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Install Playwright
        working-directory: frontend
        run: npx playwright install --with-deps
      - name: Run dev server
        working-directory: frontend
        env:
          VITE_API_URL: 'http://localhost:8000/api'
        run: |
          nohup npm run dev -- --host 0.0.0.0 >/dev/null 2>&1 &
          sleep 3
      - name: E2E tests
        working-directory: frontend
        env:
          E2E_BASE_URL: 'http://localhost:5173'
        run: npm run e2e
